name: Erlang rebar CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version: ["23.3", "23.2", "23.1", "23.0", "22.3", "22.2", "22.1", "22.0", "21", "20", "19", "18"]
        rebar: [rebar, rebar3]
    container:
      image: erlang:${{ matrix.version }}
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: ${{ matrix.rebar }} compile
    - name: XRef
      run: ${{ matrix.rebar }} xref
